### ISSUE TITLE
Precompiled NIFs do not work on Fedora and Red Hat machines

### ISSUE THREAD

**Issue by Benjamin-Philip** [philss/rustler_precompiled#30]
This is because redhat uses the following target `x86_64-redhat-linux`. Other than a change in OS target variant and the missing "gnu" suffix, there is (as far as I know) no difference between ` x86_64-redhat-linux` and x86_64-unknown-linux-gnu.

Possible solutions include:

- Adding the redhat target to the default list
- Changing the target validation logic to conform to a regex instead of a concrete list of targets
- Writing documentation warning users to add the redhat and other such targets to builds.

Personally I prefer the 2nd option.

**Comment by philss** [comment]
I would use a list in the [normalization code](https://github.com/philss/rustler_precompiled/blob/d5178fc9e88cdb6d3876016708feb0c431e28c19/lib/rustler_precompiled.ex#L384) to treat "redhat" as "unknown". WDYT?
