### ISSUE TITLE
TARGET_VENDOR, Unable to override the environment variable

### ISSUE THREAD

**Issue by m0rt3nlund** [philss/rustler_precompiled#70]
Hi!

Is there a special reason why I cannot override the `vendor`?

If I try to set it to `TARGET_VENDOR="pc"` it is reset back to `unknown`

The reason why I ask is that i am using `Burrito` to cross compile my application.
My host is Linux and the target is Windows.

I am compiling using this environment variables:

```
ENV TARGET_ARCH="x86_64"
ENV TARGET_VENDOR="pc"
ENV TARGET_OS="windows"
ENV TARGET_ABI="msvc"
```

The result I get is this:
```
 == Compilation error in file lib/thumbp.ex ==
21.93 ** (RuntimeError) precompiled NIF is not available for this target: "x86_64-unknown-windows-msvc".
21.93 The available targets are:
21.93  - aarch64-apple-darwin
21.93  - aarch64-unknown-linux-gnu
21.93  - aarch64-unknown-linux-musl
21.93  - arm-unknown-linux-gnueabihf
21.93  - riscv64gc-unknown-linux-gnu
21.93  - x86_64-apple-darwin
21.93  - x86_64-pc-windows-gnu
21.93  - x86_64-pc-windows-msvc
21.93  - x86_64-unknown-linux-gnu
21.93  - x86_64-unknown-linux-musl
21.93     lib/thumbp.ex:8: (module)
```

This tells me that the vendor is not something I can override?
Looking into the [source code](https://github.com/philss/rustler_precompiled/blob/b14698b68e140ae4652eb3bed7f0113042acaf2a/lib/rustler_precompiled.ex#L508) it looks like this is done for a reason, which i cannot fully understand :)

**Comment by philss** [comment]
Sorry for the delay. This will be fixed in the next patch.
