### ISSUE TITLE
** (FunctionClauseError) no function clause matching in anonymous fn/1 in RustlerPrecompiled.available_nif_urls/1 

### ISSUE THREAD

**Issue by satoren** [philss/rustler_precompiled#82]
Starting with version 0.8.0, it seems that specifying a simple URL for base_url no longer works.

You can see the error message [here](https://github.com/satoren/y_ex/actions/runs/10756369822/job/29829170577#step:5:281).

The error message seems to indicate [this line](https://github.com/philss/rustler_precompiled/blob/47743ca0227a2785f8851b220a27f261e92708da/lib/rustler_precompiled.ex#L281).

**Comment by philss** [comment]
Hey, thanks! I will check this ASAP tomorrow.
Cc / @sliiser

**Comment by philss** [comment]
Fixed and released. Thank you for the report!
