### ISSUE TITLE
:rustler_precompiled only looks at :castore for CA certificates, ignoring user set CA certs

### ISSUE THREAD

**Issue by DnOberon** [philss/rustler_precompiled#84]
https://github.com/philss/rustler_precompiled/blob/8d7ce94fe089c2a313f05bb7c66c999e714aad86/lib/rustler_precompiled.ex#L927

I'm behind a corporate ZScaler firewall and consistently have to set my own CA certificates. Typically, libraries have respected the env var `HEX_CACERTS_PATH`  for adding any user specified certs to the chain. Looking here however, it appears that the only source referenced is the `:castore` module - overwriting any user-set preference.

I can make changes to have this respect user-set certs, but I want to see what your thoughts are on how you'd like that done, so I don't waste any time in doing something you'd never approve of.

**Comment by philss** [comment]
@DnOberon I would say it's fine to try to read the `HEX_CACERTS_PATH` and check if the path exists, and if not, default to `CAStore`. We could also have our env var, but I would start with Hex's one first. WDYT?

**Comment by DnOberon** [comment]
Sounds great to me. Should I do it and open a PR for it when I’m done?

**Comment by philss** [comment]
@DnOberon yes, please go ahead :)

**Comment by DnOberon** [comment]
@philss  - https://github.com/philss/rustler_precompiled/pull/85 super simple change, hopefully that works

**Comment by DnOberon** [comment]
Corrected the issue on my PR. I'd forgotten to unset the env var for the test 😮‍💨

**Comment by DnOberon** [comment]
Works perfectly now @philss ! Thank you I'll go ahead and close!
